version: '3'

services:

  zookeeper:
    env_file:
      - .env
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  broker:
    env_file:
      - .env
    image: confluentinc/cp-kafka:latest
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"

networks:
  default:
    external:
      name: kafka-network