version: "3.5"

services:

  logstream:
    build:
      context: ./producer
    container_name: logstream
    volumes:
      - ./producer:/code
    ports:
      - 8000:8000
    depends_on:
      - broker

  zookeeper:
    env_file:
      - .env
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  broker:
    env_file:
      - .env
    image: confluentinc/cp-kafka:latest
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
